LV1 = '<span class="lv lv1"></span>'
LV2 = '<span class="lv lv2"></span>'
DELETE = ['16-01', '16-02', '16-03', '16-04', '16-09']
PAGES = [
('16-01', '16-01-graphs.md', '# Chapter 16 - Graphs & Dependency\n\n## Graphs ' + LV1, [
 '- **What it is:** the statement describes relationships, not a sequence: "A is friends with B", "course C needs D". Items are nodes, relationships edges',
 '- **Signal:** items 0 to n − 1 with pairs, "connected", "fewest steps", "X before Y", "share something"',
 '- **Mechanism:** once the edge is named, the question is standard: reach and group (BFS, DFS, union–find), shortest paths (BFS, Dijkstra), order (topological sort), each in Module 05',
], [
 '### The moves',
 '',
 '| Move | When to use | What it exploits |',
 '|---|---|---|',
 '| **16-02** | the statement never says "edge" | a shared value, a range, a ratio is one |',
 '| **16-03** | "enclosed", "surrounded" | flood what is *not* enclosed |',
 '| **16-04** | "X before Y", build order | in-degree 0 is always safe |',
 '| **18-02** | cheapest path, weighted steps | a heap keyed on the cost |',
 '',
 '### The skeleton: BFS',
 '',
 '```ts',
 'const adj: number[][] = Array.from({ length: n }, () => []);',
 'for (const [u, v] of edges) { adj[u].push(v); adj[v].push(u); }',
 'const dist = new Array(n).fill(-1), q = [src];',
 'dist[src] = 0;',
 'for (let h = 0; h < q.length; h++)               // a head index, not shift()',
 '  for (const v of adj[q[h]])',
 '    if (dist[v] < 0) { dist[v] = dist[q[h]] + 1; q.push(v); }',
 '```',
 '',
 '### The trap',
 '',
 '- **Building the graph literally.** Comparing every pair of items to find edges is O(n²) before the search starts. Generate neighbours on the fly, or index by the shared value (16-02)',
], None, None),

('16-02', '16-02-find-the-hidden-edge.md', '## Find the Hidden Edge ' + LV2, [
 '- **What:** three edges hide in statements: two items **share** a value, one **reaches** another within a range, or one is a **ratio** of another',
 '- **Spot it:** "accounts sharing an email", "bombs in range", "a / b = 2.0". Fewest steps → 16-01',
 '- **Why:** connectivity is transitive, so union–find merges groups in near-constant time per edge. Index by the shared value: one union per value',
], [
 '- **Watch out:** union–find on a *directed* relation: bomb A reaching B does not mean B reaches A. BFS from each bomb instead',
 '- **Also solves:** {LC 1319} · {LC 990} · {LC 399}',
], '16-02', '16-02'),

('16-03', '16-03-flood-from-the-border.md', '## Flood from the Border ' + LV2, [
 '- **What:** invert the question. Flood inward from the border and mark everything reached as **safe**; whatever the flood never touched is enclosed',
 '- **Spot it:** "surrounded", "enclosed", "closed island", "can reach the ocean". Regions only counted → one flood each, Module 05',
 '- **Why:** "touches the border" belongs to a whole region, so one flood from the border settles every region at once: O(m · n)',
], [
 '- **Watch out:** asking each region with `dfs(down) && dfs(up) && …`: it stops at the first border hit and leaves the region half-visited',
 '- **Also solves:** {LC 1020} · {LC 1254} (sink border islands first) · {LC 417}',
], '16-03', '16-03'),

('16-04', '16-04-order-the-dependencies.md', '## Order the Dependencies ' + LV1, [
 '- **What:** one task unlocks another, so the work is a DAG (a directed graph with no cycle). Kahn\'s algorithm processes a node once its in-degree is 0, then lowers its neighbours\'',
 '- **Spot it:** "prerequisites", "build order", "X must finish before Y", "minimum time if independent tasks run in parallel", "the letter order implied by a sorted word list"',
 '- **Why:** a node with no unfinished prerequisite is always safe next. Fewer than n nodes processed means a cycle. The longest chain, not the number of tasks, sets the finish time',
], [
 '```ts',
 '// Parallel Courses III (LeetCode 2050): relations[i] = [prev, next], 1-indexed',
 'function minimumTime(n: number, relations: number[][], time: number[]): number {',
 '  const adj: number[][] = Array.from({ length: n }, () => []);',
 '  const indeg = new Array(n).fill(0);',
 '  for (const [a, b] of relations) { adj[a - 1].push(b - 1); indeg[b - 1]++; }',
 '  const finish = time.slice(), q: number[] = [];',
 '  for (let v = 0; v < n; v++) if (indeg[v] === 0) q.push(v);',
 '  for (let h = 0; h < q.length; h++) {             // in-degree 0: safe next',
 '    const u = q[h];',
 '    for (const v of adj[u]) {',
 '      finish[v] = Math.max(finish[v], finish[u] + time[v]);',
 '      if (--indeg[v] === 0) q.push(v);',
 '    }',
 '  }',
 '  return Math.max(...finish);',
 '}',
 '```',
 '',
 '- **Watch out:** summing every duration treats the tasks as sequential. Independent tasks run together; only the longest chain counts',
 '- **Also solves:** {LC 207} · {LC 210} (the Kahn order itself) · [Alien Dictionary](https://www.geeksforgeeks.org/problems/alien-dictionary/1) (GFG) (an edge per first differing letter)',
], '16-04', None),

('16-09', '16-09-graph-drills.md', '## Drills: Graphs & Dependency ' + LV2, [
 'The most-asked problems for this chapter. Cover the right column and name the page first.',
 '',
 '| Problem | Page · the deciding fact |',
 '|---|---|',
 '| {LC 200} | 16-01 · one flood per island |',
 '| {LC 721} | 16-02 · a shared email is an edge: union–find |',
 '| {LC 1319} | 16-02 · `components − 1` cables |',
 '| {LC 990} | 16-02 · union `==`, then test `!=` |',
 '| {LC 399} | 16-02 · ratios are weighted edges |',
 '| {LC 130} | 16-03 · flood from the border, flip the rest |',
 '| {LC 417} | 16-03 · two border floods, uphill |',
 '| {LC 1254} | 16-03 · sink border islands first |',
 '| {LC 207} | 16-04 · Kahn: fewer than n processed is a cycle |',
 '| {LC 210} | 16-04 · the Kahn order |',
 '| {LC 2050} | 16-04 · longest chain in Kahn order |',
], [], None, None),
]
